package com.bank.bian.customerrelationshipmanagement;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Customer Relationship Management
 *
 * Business Area:      Sales and Service
 * Business Domain:    Customer Management
 * Functional Pattern: Direct
 * Asset Type:         Customer Relationship
 * Control Record:     Customer Relationship Strategy
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Customer Relationship Management — BIAN Semantic API")
                .description("Service Domain 'Customer Relationship Management' (Direct pattern) "
                        + "operating on the 'Customer Relationship Strategy' control record.")
                .version("0.1.0"));
    }
}
